# Generated by Django 3.0.8 on 2020-07-25 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_username', models.CharField(max_length=50, verbose_name='slot_host_username')),
                ('status', models.IntegerField(verbose_name='slot_status')),
                ('date', models.DateField(verbose_name='slot_date')),
                ('start_time', models.DateTimeField(verbose_name='slot_time_start')),
                ('end_time', models.DateTimeField(verbose_name='slot_time_end')),
            ],
            options={
                'verbose_name': 'slot_data',
                'verbose_name_plural': 'slot_datas',
            },
        ),
    ]
