# Generated by Django 3.0.8 on 2020-07-25 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookIt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='user',
        ),
    ]
