# Generated by Django 3.0.8 on 2020-07-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookIt', '0002_auto_20200725_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='status',
            field=models.IntegerField(choices=[('Available', 'Available'), ('Booked', 'Booked')], verbose_name='slot_status'),
        ),
    ]
