# Generated by Django 3.0.8 on 2020-07-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookIt', '0002_remove_slot_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='host',
            field=models.CharField(default='sam', help_text='host user name', max_length=30),
            preserve_default=False,
        ),
    ]
