# Generated by Django 3.0.8 on 2020-07-25 05:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BookIt', '0003_auto_20200725_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='created_at',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='slot_created_at'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slot',
            name='end_time',
            field=models.TimeField(verbose_name='slot_time_end'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='start_time',
            field=models.TimeField(verbose_name='slot_time_start'),
        ),
    ]
