# Generated by Django 3.0.8 on 2020-07-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookIt', '0004_auto_20200725_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked')], max_length=10, verbose_name='slot_status'),
        ),
    ]
