# Generated by Django 3.0.8 on 2020-07-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookIt', '0004_auto_20200725_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='attendee',
            field=models.CharField(default='Empty', help_text='attendee username', max_length=30),
        ),
    ]
