# Generated by Django 3.0.8 on 2020-07-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookIt', '0005_auto_20200725_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
