# Generated by Django 3.0.8 on 2020-07-25 07:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BookIt', '0006_auto_20200725_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='host_username',
        ),
        migrations.AddField(
            model_name='slot',
            name='username',
            field=models.CharField(default=datetime.datetime(2020, 7, 25, 7, 12, 10, 456383, tzinfo=utc), max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slot',
            name='created_at',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='slot',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='slot',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='slot',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='slot',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked')], max_length=10),
        ),
    ]
